spring:
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    password: paascloud@redis
    port: 6379
    timeout: 0
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    initial-size: 10
#    min-idle: 10
#    max-active: 20
#    test-on-borrow: true
  mail:
    host: test.com
    username: abc@test.com
    password: test123
    port: 465
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
          ssl:
            enable: true    
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  #无论是请求超时或者socket read timeout都进行重试  
  OkToRetryOnAllOperations: false
  ConnectTimeout: 10000
  ReadTimeout: 30000
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 160000
paascloud:
  server:
    eureka:
      port: 8761
      hostname: paascloud-eureka
      serviceUrl: http://jxEurke:eurkepwd=123@paascloud-eureka:8761/eureka/
    discovery:
      port: 8080
      hostname: paascloud-discovery
      serviceUrl: http://jxConfig:configPwd999@paascloud-discovery:8080
    gateway:
      port: 80
      hostname: paascloud-gateway
    monitor:
      port: 8010
      hostname: paascloud-monitor
      serviceUrl: http://paascloud-monitor:8010
    zipkin:
      port: 8020
      hostname: paascloud-zipkin
      serviceUrl: http://paascloud-zipkin:8020
    provider:
      ehc:
        port: 8040
        hostname: paascloud-provider-ehc
      mdc:
        port: 8030
        hostname: paascloud-provider-mdc
      omc:
        port: 8050
        hostname: paascloud-provider-omc
      opc:
        port: 8070
        hostname: paascloud-provider-opc
      ptc:
        port: 8060
        hostname: paascloud-provider-ptc
      uac:
        port: 8100
        hostname: paascloud-provider-uac
    web:
      mall:
        port: 9000
        hostname: paascloud-web-mall
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  aliyun:
    key:
      accessKeyId: yourAliyunAccessKey
      accessKeySecret: '{cipher}AQBF/u1hdyQ0GASmbqL2PXXYHAUgHJg0JVtCqm3SnYJ6oxVVMnO298Mp4NerHg4FsZ9MdmoAc/yhYEJZ4whsw4X6wRHOmA4nYJnfvcakQF8FqOqUZViRK3ZHWPaeXRdzk7DkyfPOpe6uRoDVzWumT2XMmkhy6vztdlPOQdkvIM7ubNLk1cYHsS2dX+5B5C81R+WZ1R6E9uDeNsSY09a/06IQY6mIesH37YdaLCkdaMQ6S/LB/oNAKvaknJLXQ72ViH2vuu2p8GGFUmSX8REWQfC0oSPZuz69dNvLDyoukES5KqMZ3VNp7aC9NsVW+VrOJfFUtoVyZAmdnh9mgyRny57ztWSfVQZ82lQDfUYalsucQt0KDFhJb4mxddON+jZ6VwQ='
    rocketMq:
      namesrvAddr: 127.0.0.1:9876
    sms:
      signName: 测试
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  zk:
    zkAddressList: paascloud-provider-zk:2181