#主从数据库配置
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_tpc?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        initial-size: 10
        min-idle: 10
        max-active: 30
        test-on-borrow: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        web-stat-filter:
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        stat-view-servlet:
          allow:
          login-username: admin
          login-password: admin        
#    slave:
#        url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_tpc_read?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
#        driver-class-name: com.mysql.jdbc.Driver
#        username: root
#        password: 123456
#        initial-size: 10
#        min-idle: 10
#        max-active: 30
#        test-on-borrow: true
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        web-stat-filter:
#          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#        stat-view-servlet:
#          allow:
#          login-username: admin
#          login-password: admin
server:
  port: ${paascloud.server.provider.tpc.port:8090}
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
  zipkin:
    base-url: http://paascloud-zipkin:8020
  sleuth:
    sampler:
      percentage: 1.0
spring:
  cache:
    cache-names: tpc-cache
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_tpc?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.paascloud.provider.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.paascloud.core.mybatis.MyMapper
  not-empty: true
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: paascloud-client-mdc
      clientSecret: paascloudClientSecret
      access-token-uri: http://paascloud-provider-uac:8100/uac/oauth/token
      user-authorization-uri: http://paascloud-provider-uac:8100/uac/oauth/authorize
    resource:
      user-info-uri: http://paascloud-provider-uac:8100/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://paascloud-provider-uac:8100/uac/oauth/token_key

paascloud:
  enableSqlLogInterceptor: false
  dingTalk:
    webhookToken:
      jobListener: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
  token:
    interceptor:
      enable: true
  message:
    maxSendTimes: 7
    handleTimeout: 60
    resendMultiplier: 2
  aliyun:
    rocketMq:
      enable: false
      reliableMessageConsumer: false
      reliableMessageProducer: true
      namesrvAddr: paascloud-mq-rocket:9876
      instanceName: paascloud-provider-tpc
      producerGroup: PID_TPC
  oauth2:
    jwtSigningKey: paascloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  zk:
    namespace: paascloud-elastic-job
  job:
    task:
      dingTalk:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      sendingMessage:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        jobParameter: fetchNum=200,taskType=SENDING_MESSAGE
      waitingMessage:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        jobParameter: fetchNum=200,taskType=WAITING_MESSAGE

dataflowJob:
  cron: 0 */20 * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
eureka:
  instance:
    hostname : paascloud-provider-tpc