#主从数据库配置
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_opc?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: '{cipher}91047b1bff364f8f7ddf9488691d9812b78e47565175b1c8dce5524f2f36cf4f'
        initial-size: 10
        min-idle: 10
        max-active: 30
        test-on-borrow: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        web-stat-filter:
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        stat-view-servlet:
          allow:
          login-username: admin
          login-password: admin        
#    slave:
#        url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_opc_read?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
#        driver-class-name: com.mysql.jdbc.Driver
#        username: root
#        password: 123456
#        initial-size: 10
#        min-idle: 10
#        max-active: 30
#        test-on-borrow: true
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        web-stat-filter:
#          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#        stat-view-servlet:
#          allow:
#          login-username: admin
#          login-password: admin
server:
  port: 8070
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_opc?useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
  zipkin:
    base-url: http://paascloud-zipkin:8020
  sleuth:
    sampler:
      percentage: 1.0    
liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.paascloud.provider.model.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.paascloud.core.mybatis.MyMapper
  not-empty: true
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: paascloud-client-opc
      clientSecret: '{cipher}dc47331dd22b22ac3b641a83a201fd51bd1def71437f3bcc0f49fc6c58c4d1545d2168fbc18260c731097040da750271'
      access-token-uri: http://paascloud-provider-uac:8100/uac/oauth/token
      user-authorization-uri: http://paascloud-provider-uac:8100/uac/oauth/authorize
    resource:
      user-info-uri: http://paascloud-provider-uac:8100/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://paascloud-provider-uac:8100/uac/oauth/token_key

paascloud:
  enableSqlLogInterceptor: false
  token:
    interceptor:
      enable: true
  zk:
    oss:
      privateHost:
      publicHost:
      fileMaxSize: 104857600
  oauth2:
    jwtSigningKey: '{cipher}b11f2e852b3aad2bef83867100b4064759deb60890475fa61ff7b6e0b2f1ade7e36385a96279eb72176051ab1cbca4a4'
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  aliyun:
    rocketMq:
      enable: true
      reliableMessageConsumer: true
      reliableMessageProducer: false
      namesrvAddr: paascloud-mq-rocket:9876
      instanceName: paascloud-provider-opc
      consumerGroup: CID_OPC
      producerGroup: PID_OPC
  qiniu:
    oss:
      public-host: http://qiniu.qzjxcy.com
      privateHost: http://qiniu.qzjxcy.com
      fileMaxSize: 104857600            
eureka:
  instance:
    hostname : paascloud-provider-opc